#config_version=6

mode:
  start_events: mission_select_hank_mini_wizard_selected{current_player.any_mb_active == 0}
  stop_events: ball_ended, timer_hank_mini_wizard_mode_countdown_complete
  priority: 130

slide_player:
  mode_hank_mini_wizard_started: hank_mini_wizard

timers:
  hank_mini_wizard_mode_countdown:
    start_value: 5
    end_value: 0
    direction: down
    start_running: true
    bcp: true

variable_player:
  timer_hank_mini_wizard_mode_countdown_complete:
    modes: 1
